name: Run tests

on:
  pull_request:
    branches:
      - develop
      - release**
      - master
  workflow_dispatch:

env:
  PACT_BROKER_BASE_URL: https://poc-test.pactflow.io
  PACT_BROKER_TOKEN: ${{ secrets.PACTFLOW_TOKEN_FOR_CI_CD_WORKSHOP }}
  REACT_APP_API_BASE_URL: http://localhost:8080
  GIT_COMMIT: ${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '12'
      - name: Install
        run: npm i
      - name: Tests
        run: make test
      - name: Publish pacts
        run: | 
          echo ${GITHUB_HEAD_REF}
          echo ${GITHUB_BASE_REF}
          echo ${GITHUB_REF}
          echo ${GITHUB_REF_NAME}
          GIT_BRANCH=${GITHUB_HEAD_REF} make publish_pacts

  # Runs on branches as well, so we know the status of our PRs
  # GITHUB_HEAD_REF for pull_request:
  can-i-deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - run: docker pull pactfoundation/pact-cli:latest
      - name: Can I deploy?
        run: GIT_BRANCH=${GITHUB_HEAD_REF} make can_i_deploy